#!/usr/bin/env bash
# Script that install nginx on server

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx start
