#!/usr/bin/env bash
# COnfigures a new Ubuntu machine with custom header

sudo apt-get update
sudo apt-get -y install nginx

sudo allow ufw 'Nginx HTTP'

echo "add_header X-Served-By \$hostname;" >> /etc/nginx/sites-available/default

sudo service nginx restart
