#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server

# Update the package list
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  kharisrem-frontend
        bind *:80
        mode http
        default_backend kharisrem-backend
backend kharisrem-backend
        balance roundrobin
        server 397684-web-01 52.86.65.66:80 check
        server 397684-web-02 35.153.79.9:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
