#!/usr/bin/env bash
# This script ensures Nginx is running and listening on port 80 for all active IPv4 IPs.
# Delete the existing ../sites-enabled/default and replacing it with a copy of
# ../sites-available/default. This is done by creating a symbolic link.
# Note: The flag -s creates a symbolic link, -f deletes the existing file and replaces it.

# Remove existing symbolic link to default configuration
sudo rm -f /etc/nginx/sites-enabled/default

# Create a new symbolic link to the default configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
