#!/usr/bin/env bash
# Display the time for 12 hour to 59 minutes

# display hour from 0 to 12
# display minutes from 1 to 59

# Requirement
# You must use the while loop (for and until are forbidden)
#Note that in this example, we only display the first 70 lines using the head command.

hour=0
while [ $hour -lt 12 ]
do
	echo "Hour: $hour"
	min=1
	while [ $min -lt 60 ]
	do
		echo $min
		min=$((min+1))
	done
	hour=$((hour+1))
done

echo "Hour: 12"
min=1
while [ $min -lt 60 ]
do
	echo $min
	min=$((min+1))
done
