#!/usr/bin/env bash
#
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
#
# Requirements:
# You must use the for loop (while and until are forbidden)
# Do not display hidden files

list=$(ls)
for i in $list
do
    echo "$i" | cut -d'-' -f 2
done
