#!/usr/bin/env bash
# Script that Fix this container so that Nginx is running as the nginx user.

# Set the Nginx user in the configuration
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Replace port 80 with 8080 in the default site configuration
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Give read and write permissions to the owner for the Nginx configuration file
chmod 644 /etc/nginx/nginx.conf

# Kill the Apache process if it is running to avoid interference with Nginx
pkill apache2

# Start the Nginx service with the new Nginx user
sudo -u nginx service nginx start
